github:
  - .github/**/*

docs:
  - docs/**/*
  - **/*.md

src:
  - src/**/*

test:
  - test/**/*
  - jest.config.js

lint:
  - .eslint*
  - .prettier*
  - .markdownlint*
  - .editorconfig
  - commitlint*

nvm:
  - .nvmrc

git:
  - .gitignore
  - .gitattributes
  - .gitmodules

build:
  - package.json
  - yarn.lock
  - package-lock.json
  - tsconfig.json

editor:
  - .vscode/**/*
  - .idea/**/*


