name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8, 9, 10, 11, 12]
        os: [ubuntu-latest, macOS-latest, windows-latest, windows-2016]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --ignore-scripts --ignore-engines
        env:
          CI: true

      - name: Test And Measure Coverage
        run: |
          yarn test:coverage \
          --ci

      - name: Lint
        run: yarn lint

      - name: Use Node.js 10.x # for unauthenticated publish, npm version shold be high
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Run Local Npm Registry On Windows
        if: startsWith(matrix.os, 'windows')
        # verdaccio is private npm registry. [link](https://github.com/verdaccio/verdaccio/)
        run: |
          docker-compose --project-name verdaccio --file ./verdaccio/docker-compose.yml up -d

      - name: Run Local Npm Registry on Linux Or macOS
        if: startsWith(matrix.os, 'windows') == false # use an operrator "==" as "!startsWith(matrix.os, 'windows')" causes an error
        # trailing `&` detaches process from foreground
        run: |
          npm install --global verdaccio
          verdaccio --config ./verdaccio/conf/default.yaml &
          sleep 10

      - name: Publish To Local NPM Registry
        # waits 10 seconds until verdaccio (probably) becomes ready
        run: npm publish --registry http://localhost:4873

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Installation
        run: |
          npm install --global hasura-cli --registry http://localhost:4873
          hasura version
          npm uninstall --global hasura-cli

# TODO: publish (Check git version tag(e.g. v1.0.0-beta.7))
